FROM alpine:3.22.1
 
LABEL maintainer="alpine-gcc-base:3.22.1"
#更新Alpine的软件源为国内（清华大学）的站点，因为从默认官源拉取实在太慢了。。。
RUN echo "https://mirror.tuna.tsinghua.edu.cn/alpine/v3.22/main/" > /etc/apk/repositories
 
RUN apk update \
    && apk upgrade \
    && apk add --no-cache bash \
    bash-doc \
    bash-completion \
    gcc \
    && rm -rf /var/cache/apk/*