# buildah 与 qemu-user-static配合用于交叉编译的最小镜像
FROM alpine:3.22.1
RUN apk update \
    && apk add --no-cache bash buildah qemu-user-static libssl-dev  curl  xz-utils wget openssh-server vim  jq  git\
    && wget https://raw.githubusercontent.com/aspnmy/debian_ssh.s6-overlay/refs/heads/devbox/Dockerfile/app/bin/setRootKey_Cli.sh \
    && bash setRootKey_Cli.sh superman\
    && rm -rf /var/lib/apt/lists/*

CMD ["/bin/bash"]
